### ISSUE TITLE
Improve Synapse event posting performance

### ISSUE THREAD

**Issue by feature** [SerenityEnterprises/SerenityCE#4] opened 2017-10-07 16:53 UTC
### Issue description
Each time the `EventManager.post` method is called, all the registered listeners' event target class is matched against the class of the `event` being posted. This causes a lot of unnecessary overhead when listeners of different event targets are registered, which will exponentially impact performance for each event posting.

**Comment by char** [comment] 2017-10-07 16:54
Psuedo-duplicate of #3.

**Comment by char** [comment] 2017-10-08 02:43
Closed by pull request #5

**Closed as completed by char** 2017-10-08 02:43 UTC
